# Generated by Django 4.2.16 on 2024-11-07 02:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessibilityFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_host_provided', models.BooleanField(default=False, help_text='True if this feature was provided by the host')),
            ],
        ),
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Dorm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type_of_dorm', models.CharField(choices=[('Single Room', 'Single Room'), ('Double Room', 'Double Room'), ('Deluxe Room', 'Deluxe Room'), ('Apartment Style', 'Apartment Style')], max_length=255)),
                ('area', models.DecimalField(decimal_places=2, help_text='Area in square feet', max_digits=10)),
                ('bathroom', models.PositiveIntegerField()),
                ('study_area', models.PositiveIntegerField()),
                ('availability_status', models.BooleanField(default=True)),
                ('reviews_count', models.PositiveIntegerField(default=0)),
                ('reviews_avg_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('accessibility_features', models.ManyToManyField(blank=True, related_name='dorms', to='base.accessibilityfeature')),
                ('amenities', models.ManyToManyField(blank=True, related_name='dorms', to='base.amenity')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(max_length=100)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('comment', models.TextField()),
                ('dorm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='base.dorm')),
            ],
        ),
        migrations.CreateModel(
            name='RentalCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('utilities', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dorm', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.dorm')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('display_name', models.CharField(max_length=100)),
                ('occupation', models.CharField(default='Student', max_length=100)),
                ('legal_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('id_document_type', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('google_map_embed_code', models.TextField(blank=True, null=True)),
                ('nearby_schools', models.IntegerField()),
                ('grocery_stores', models.IntegerField()),
                ('hospitals', models.IntegerField()),
                ('malls', models.IntegerField()),
                ('coffee_shops', models.IntegerField()),
                ('transit_options', models.CharField(max_length=255)),
                ('dorm', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.dorm')),
            ],
        ),
        migrations.CreateModel(
            name='DormImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='dorm_images/')),
                ('dorm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='base.dorm')),
            ],
        ),
    ]
