# Generated by Django 4.2.16 on 2024-11-07 03:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0002_favoritedorm'),
    ]

    operations = [
        migrations.AddField(
            model_name='dorm',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_dorms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Owner', 'Owner'), ('Hunter', 'Hunter')], default='Hunter', max_length=10),
        ),
    ]
