# Generated by Django 4.2.16 on 2024-11-07 03:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0003_dorm_owner_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dorm',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_dorms', to=settings.AUTH_USER_MODEL),
        ),
    ]
