# Generated by Django 4.2.16 on 2024-11-07 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_dorm_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='dorm',
            name='place_type',
            field=models.CharField(choices=[('Single Room', 'Guests will have their own private space within a larger accommodation'), ('Shared Room', 'Guests will have their own private space within a larger accommodation'), ('Entire Place', 'Guests will have the whole place to themselves, offering privacy and freedom')], help_text='What type of place will guests have?', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dorm',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
