# Generated by Django 4.2.16 on 2024-11-07 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_dorm_place_type_dorm_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.AlterField(
            model_name='dorm',
            name='availability_status',
            field=models.BooleanField(default=False),
        ),
    ]
