# Generated by Django 4.2.16 on 2024-11-07 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_profile_email_alter_dorm_availability_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='dorm',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
