# Generated by Django 4.2.16 on 2024-11-07 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_dorm_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dorm',
            name='bathroom',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dorm',
            name='study_area',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
