# Generated by Django 4.2.16 on 2024-11-07 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_dorm_bathroom_alter_dorm_study_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='dorm',
            name='bed',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='dorm',
            name='bedroom',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
