# Generated by Django 4.2.16 on 2024-11-07 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_dorm_bed_dorm_bedroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='dorm',
            name='guest',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
