# Generated by Django 4.2.16 on 2024-11-07 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_dorm_guest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dorm',
            name='bathroom',
            field=models.IntegerField(null=True),
        ),
    ]
