# Generated by Django 4.2.16 on 2024-11-07 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_dorm_bathroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dorm',
            name='bathroom',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
