# Generated by Django 4.2.16 on 2024-11-07 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_dorm_bathroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalcost',
            name='deposit',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='rentalcost',
            name='utilities',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
