# Generated by Django 4.2.16 on 2024-11-08 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_rentalcost_deposit_alter_rentalcost_utilities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dorm',
            name='guest',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
