# Generated by Django 4.2.11 on 2024-11-08 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_dorm_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dorm',
            name='bathroom',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='dorm',
            name='bed',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='dorm',
            name='bedroom',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='dorm',
            name='study_area',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
